export type ServiceContent = {
  slug: string
  title: string
  tagline: string
  price?: string
  intro: string
  image: string
  expertise: [string, string][]
  includes: [string, string][]
  steps: [string, string][]
  audience: string[]
  suggestions: string[]
}

const common = {
  steps: [
    ['Discovery & Requirements', 'We clarify your goals, audience, timeline, and success measures.'],
    ['Specialist Strategy', 'We pair your project with the right expertise and map the work clearly.'],
    ['Build, Review & Refine', 'You review the work at key milestones and request revisions.'],
    ['Delivery & Ongoing Support', 'We hand over polished deliverables with practical next steps.'],
  ] as [string, string][],
}

export const serviceContent: Record<string, ServiceContent> = {
  'academic-writing': {
    slug: 'academic-writing', title: 'Academic & Research', tagline: 'Expert Writers · Fast Turnaround · $8/page', price: '$8/page', image: '/tutor-1.jpg',
    intro: 'Academic life comes with constant deadlines, dense research requirements, and formatting rules that differ from one professor to the next. Our Academic & Research team pairs you with subject-matter writers and editors who understand exactly what markers and supervisors are looking for. Whether you need a single essay polished or a full dissertation structured from scratch, we combine subject expertise with rigorous quality checks so every paper you submit is well-researched, properly cited, and entirely your own voice — refined.',
    expertise: [['Essay & Research Paper Writing','Original, well-argued papers researched from credible academic sources.'],['Thesis & Dissertation Support','Chapter-by-chapter guidance from proposal to final defense draft.'],['Editing & Proofreading','Grammar, structure, and clarity review that keeps your own voice intact.'],['Citation & Referencing','Accurate formatting in APA, MLA, Harvard, Chicago, and more.'],['Plagiarism & Originality Checks','Every paper is scanned and reported before delivery.'],['Subject-Specific Research Assistance','Writers matched to your exact field of study.']],
    includes: [['Undergraduate & Postgraduate Papers','Across all major subject areas.'],['Literature Reviews','Research synthesized clearly and critically.'],['Case Studies & Reports','For business, law, health, and social science courses.'],['Presentation & Slide Support','Written submissions supported by clear slides.'],['Statistical Analysis for Research','Data interpretation and write-up support.'],['Rush & Same-Day Delivery','Tight deadlines handled without sacrificing quality.']],
    steps: [['Share Your Requirements','Send us the brief, rubric, and deadline.'],['Get Matched With a Specialist','Work with a writer in your subject area.'],['Review Your Draft','Request revisions at no extra cost.'],['Receive Your Final Paper','Fully cited and plagiarism-checked.']], audience:['Undergraduate and postgraduate students managing multiple deadlines','Researchers who need editing or formatting support before submission','Professionals returning to study who want expert writing guidance'], suggestions:['Personal Statement & Application Essay Writing','Plagiarism Removal & Paraphrasing Service'], ...common,
  },
  'reputation-management': {
    slug:'reputation-management', title:'Reputation Management', tagline:'Real Reviews · Rating Boost · Proven Results', image:'/service-digital-marketing.png', intro:'Your rating is often the first thing a potential customer sees — and the deciding factor in whether they choose you or a competitor. We help businesses build a stronger, more accurate online reputation through ethical review generation, proactive monitoring, and strategic response management across every major platform. The result is a public profile that actually reflects the quality of what you do, backed by real feedback from real customers.',
    expertise:[['Review Generation Campaigns','Ethical, compliant strategies that encourage happy customers to leave feedback.'],['Reputation Monitoring & Alerts','Know the moment a new review or mention appears.'],['Negative Review Response Strategy','Professional responses that protect your brand and resolve issues publicly.'],['Google Business Profile Optimization','A fully optimized profile that ranks and converts better.'],['Cross-Platform Rating Management','Consistent reputation across Google, Amazon, Airbnb, and Glassdoor.'],['Reputation Recovery Plans','Structured plans to rebuild trust after a rough patch.']], includes:[['Google, Amazon, Airbnb & Glassdoor','Review strategy and management across key platforms.'],['Review Request Automation','Triggered at the right moment in the customer journey.'],['Monthly Reputation Reports','Rating trends and sentiment made clear.'],['Competitor Reputation Benchmarking','Know where you stand in your market.'],['Crisis Response Support','Support for sudden negative attention.'],['Employer Brand Reputation','Glassdoor and similar platform management.']], steps:[['Reputation Audit','We assess your current ratings, reviews, and gaps.'],['Strategy & Platform Setup','We focus on the sites that matter most to you.'],['Review Generation & Monitoring','The process runs continuously in the background.'],['Ongoing Reporting & Optimization','Your rating keeps trending upward.']], audience:['Local businesses relying on Google reviews to win new customers','Hosts and sellers on Airbnb or Amazon needing stronger ratings','Employers wanting a more attractive Glassdoor presence for hiring'], suggestions:['Social Proof Widgets for Your Website','Customer Feedback Survey Automation'], ...common,
  },
  'ai-data': {
    slug:'ai-data', title:'AI Data & Model Support', tagline:'ML Experts · Data Solutions · AI Integration', image:'/service-ai-data.png', intro:'AI is only as useful as the data and models behind it. Our AI Data & Model Support team works with founders, product teams, and researchers to turn raw, messy data into clean pipelines, working models, and real business insight. From your first prototype to a production-ready system, we handle the technical heavy lifting so you can focus on the product decisions that matter.',
    expertise:[['Machine Learning Model Development','Models built and tuned around your actual use case.'],['Data Processing & Cleaning','Raw, inconsistent data turned into something usable.'],['Predictive Analytics Solutions','Forecasting demand, churn, risk, and other key outcomes.'],['AI Algorithm Implementation','Published research and techniques brought into your product.'],['Data Visualization & Insights','Clear dashboards that make model outputs actionable.'],['Custom AI Solutions','Bespoke builds when off-the-shelf tools do not fit.']], includes:[['Model Training','Your datasets benchmarked for performance.'],['Data Pipeline Setup','Reliable, repeatable data flow.'],['NLP Solutions','Text classification, summarization, and chatbots.'],['Computer Vision','Image recognition and visual data tasks.'],['Time Series Analysis','Forecasting and trend detection.'],['Recommendation Systems','Personalized customer experiences.']], steps:[['Discovery & Data Assessment','We review your goals and existing data.'],['Model Design & Development','A solution tailored to your specific problem.'],['Testing & Validation','Real-world performance benchmarks.'],['Deployment & Ongoing Support','Support continues once the model is live.']], audience:['Startups building AI-powered products or features','E-commerce brands wanting recommendation or personalization engines','Companies sitting on raw data that needs to be cleaned, structured, and modeled'], suggestions:['AI Chatbot & Workflow Automation Setup','Data Labeling & Annotation Services'], ...common,
  },
  'web-development': { slug:'web-development', title:'Web Design & Development', tagline:'Responsive Design · Fast Performance · SEO Optimized', image:'/service-data-analytics.png', intro:'Your website is often a customer’s first real interaction with your business — it needs to load fast, look sharp on every device, and make it obvious what to do next. Our Web Design & Development team builds custom sites and web applications using modern, reliable technology, balancing clean design with real technical performance so your site does not just look good, it works hard for your business.', expertise:[['Custom Website Design','Built around your brand, not a generic template.'],['Web Application Development','Functional tools and platforms, not just static pages.'],['E-Commerce Store Development','Stores built to convert browsers into buyers.'],['Landing Page Design & Optimization','Focused pages built for a single, clear goal.'],['Website Speed & Performance Optimization','Faster load times, better rankings, fewer drop-offs.'],['API & Third-Party Integrations','Connecting your site to the tools you already use.']], includes:[['Business & Portfolio Websites','For companies and individual professionals.'],['Online Stores','Shopify, WooCommerce, or a fully custom stack.'],['Web Application Development','Internal tools or customer-facing products.'],['CMS Setup','WordPress, Webflow, or similar manageable platforms.'],['Website Redesigns','For sites that feel dated or underperform.'],['Ongoing Maintenance & Support','Your site stays fast, secure, and current.']], steps:[['Discovery & Planning','We understand your goals, audience, and content.'],['Design & Prototyping','See and approve the look before we build.'],['Development & Testing','Across devices and browsers.'],['Launch & Post-Launch Support','Fine-tune performance after launch.']], audience:['Businesses needing a professional, mobile-friendly website','Startups launching an MVP, product page, or online store','Companies whose current site is outdated, slow, or hard to update'], suggestions:['Website Maintenance & Support Plans','E-Commerce Store Setup & Conversion Optimization'], ...common },
  'digital-marketing': { slug:'digital-marketing', title:'Digital Marketing', tagline:'Organic Growth · Social Strategy · Campaign Management', image:'/service-digital-marketing.png', intro:'Growing a business online takes more than posting occasionally and hoping for the best. Our Digital Marketing team builds structured, measurable strategies across search, social, email, and paid channels so every dollar and every post is working toward a clear goal — more traffic, more leads, and more customers who actually convert.', expertise:[['Search Engine Optimization (SEO)','Ranking higher for the searches that matter to your business.'],['Social Media Management','Consistent, on-brand presence across key platforms.'],['Paid Advertising','Google and Meta campaigns built around real ROI.'],['Email Marketing Campaigns','Nurture sequences and newsletters that keep customers engaged.'],['Content Marketing Strategy','A plan tied to a clear business goal.'],['Analytics & Performance Tracking','Know exactly what is working and what is not.']], includes:[['Keyword Research & On-Page SEO','Improve organic search visibility.'],['Social Media Content Calendars','Planned, designed, and scheduled content.'],['PPC Campaign Setup & Management','Across Google and Meta Ads.'],['Email Sequences & Newsletters','Convert subscribers into customers.'],['Marketing Funnel Design','From first touch to final sale.'],['Monthly Performance Reports','Clear, honest metrics.']], steps:[['Marketing Audit & Strategy','Built around your specific goals.'],['Campaign Setup & Launch','Across the right channels for your audience.'],['Execution & Optimization','Based on real performance data.'],['Reporting & Scaling','Scale what is working best.']], audience:['Businesses wanting consistent, measurable online growth','Brands new to paid advertising needing a structured strategy','Companies wanting to build an engaged, active social following'], suggestions:['Influencer & UGC Marketing Coordination','Marketing Automation Setup'], ...common },
  'branding': { slug:'branding', title:'Branding & Creative', tagline:'Professional Design · Brand Strategy · Creative Assets', image:'/tutor-2.jpg', intro:'A strong brand does more than look good — it builds instant trust and makes your business memorable. Our Branding & Creative team develops logos, visual identities, and brand guidelines rooted in real strategy, so every touchpoint, from your business card to your website, feels consistent, professional, and unmistakably yours.', expertise:[['Logo & Visual Identity Design','A distinctive mark that represents your business well.'],['Brand Strategy & Positioning','Clarity on who you are and how you stand out.'],['Brand Guidelines Development','A reference document that keeps your brand consistent.'],['Marketing Collateral Design','Flyers, brochures, and sales materials that match your brand.'],['Packaging & Print Design','For physical products and printed materials.'],['Social Media Creative Assets','Templates and graphics built for engagement.']], includes:[['Logo Design Packages','Multiple concepts and revisions.'],['Brand Style Guides','Color, type, and usage rules.'],['Business Cards & Stationery','Polished business essentials.'],['Social Media Templates','Consistent, on-brand posting.'],['Presentation & Pitch Deck Design','For investor or client meetings.'],['Rebranding Projects','For businesses ready for a refresh.']], steps:[['Brand Discovery','Understanding your business, audience, and goals.'],['Concept Design','Multiple creative directions to choose from.'],['Refinement & Feedback','Until the design feels exactly right.'],['Final Delivery','Full brand guidelines and source files.']], audience:['New businesses needing a professional identity from scratch','Companies rebranding or refreshing an outdated look','Teams needing consistent creative assets for ongoing marketing'], suggestions:['Pitch Deck & Investor Presentation Design','Packaging Design for Physical Products'], ...common },
  'bpo': { slug:'bpo', title:'Business Process Outsourcing', tagline:'24/7 Support · Cost Effective · Scalable Team', image:'/tutor-3.jpg', intro:'Every hour your team spends on repetitive admin work is an hour not spent growing the business. Our Business Process Outsourcing team plugs in trained support staff for customer service, data entry, and administrative tasks — giving you back time and flexibility without the overhead of hiring, training, and managing an in-house team.', expertise:[['Customer Service & Support','Friendly, responsive support representing your brand well.'],['Virtual Assistance','Day-to-day support for founders and busy teams.'],['Data Entry & Management','Accurate, organized handling of your records.'],['Administrative Support','Operational tasks that keep a business running.'],['Order & Inventory Processing','Reliable handling for e-commerce operations.'],['Help Desk & Ticketing Support','Organized, tracked issue resolution.']], includes:[['Live Chat & Email Support','For your customers, on your schedule.'],['Inbound & Outbound Call Handling','Clear scripts and reporting.'],['Calendar & Inbox Management','Keep founders and executives organized.'],['CRM Data Entry & Cleanup','Records stay accurate.'],['Document Processing','High-volume administrative work.'],['Scalable Team Staffing','Support that grows with your business.']], steps:[['Needs Assessment','We understand your workload and requirements.'],['Team Setup & Onboarding','Staff matched to your needs.'],['Process Handover & Training','Nothing gets lost in transition.'],['Ongoing Support & Reporting','Track performance over time.']], audience:['Growing businesses that need support without hiring in-house','E-commerce brands needing reliable customer service coverage','Companies wanting to offload repetitive administrative work'], suggestions:['Dedicated Virtual Assistant Packages','Multilingual Customer Support Coverage'], ...common },
  'content': { slug:'content', title:'Content & Publishing', tagline:'Quality Content · SEO Writing · Consistent Publishing', image:'/tutor-4.jpg', intro:'Consistent, well-written content builds authority and drives organic traffic — but keeping up with it is hard when you are also running a business. Our Content & Publishing team researches, writes, and helps publish blog posts, articles, and web copy that sound like you, rank well, and actually get read.', expertise:[['Blog & Article Writing','Well-researched content published on a consistent schedule.'],['SEO Content Strategy','Content planned around what your audience searches for.'],['Copywriting for Websites & Ads','Persuasive copy that moves people to act.'],['Ghostwriting','Content written in your voice, credited to you.'],['Editorial Calendar Planning','A clear content schedule tied to your goals.'],['Content Repurposing','Turn one piece of content into many.']], includes:[['Weekly & Monthly Blog Packages','Consistent publishing.'],['Website & Landing Page Copy','Clear and conversion-focused.'],['Newsletter Content','Keep your audience engaged.'],['Guest Post Writing & Outreach','Build authority and backlinks.'],['Product Descriptions','For e-commerce catalogs.'],['Long-Form Guides & Whitepapers','Thought leadership assets.']], steps:[['Content Strategy & Topic Planning','Aligned to your audience and goals.'],['Writing & Research','Grounded in credible, relevant sources.'],['Review & Revisions','Until the content sounds exactly right.'],['Publishing & Distribution','Across your chosen channels.']], audience:['Brands wanting to grow organic traffic through consistent content','Businesses needing website or product copy that converts','Founders wanting to publish thought leadership without writing it themselves'], suggestions:['Podcast Show Notes & Transcription','Content Repurposing Packages'], ...common },
  'analytics': { slug:'analytics', title:'Data & Analytics', tagline:'Real-Time Insights · Data Visualization · Strategic Reports', image:'/service-data-analytics.png', intro:'Most businesses have plenty of data and not enough clarity. Our Data & Analytics team builds dashboards and reports that turn scattered numbers into clear, decision-ready insight — so you can see what is actually happening in your business at a glance, instead of digging through spreadsheets.', expertise:[['Business Intelligence Dashboards','Real-time views into the metrics that matter most.'],['Data Analysis & Reporting','Raw numbers turned into clear takeaways.'],['KPI Tracking & Performance Metrics','Know exactly how the business is performing.'],['Data Cleaning & Structuring','Reliable data for good decisions.'],['Competitive & Market Analysis','Understand where you stand in your market.'],['Forecasting & Trend Analysis','Plan ahead with more confidence.']], includes:[['Custom Dashboard Design','Power BI, Tableau, or similar tools.'],['Weekly & Monthly Reporting','Tailored to your business.'],['Sales & Revenue Analytics','Track growth and identify gaps.'],['Customer Behavior Analysis','Understand how people engage.'],['Data Warehouse Setup','For businesses scaling data needs.'],['Excel & Google Sheets Automation','For teams not ready for a full BI tool.']], steps:[['Data Audit & Goal Setting','Define what success looks like.'],['Data Collection & Cleaning','Every report uses reliable numbers.'],['Dashboard & Report Build','Tailored to your business.'],['Insights Review & Ongoing Updates','Evolve as your needs change.']], audience:['Business owners wanting clear, real-time performance visibility','Teams drowning in manual spreadsheets and reporting','Companies ready to make more data-driven decisions'], suggestions:['Automated Weekly Report Delivery','Data Strategy Consulting'], ...common },
  'technology': { slug:'technology', title:'Technology & Automation', tagline:'Process Automation · System Integration · Cost Savings', image:'/service-ai-data.png', intro:'Manual, repetitive work quietly drains time and money — and most businesses do not realize how much until it is automated away. Our Technology & Automation team streamlines workflows, connects the tools you already use, and builds custom solutions where off-the-shelf software falls short, so your operations run smoother with less manual effort.', expertise:[['Workflow & Process Automation','Remove repetitive manual steps from daily operations.'],['System & Software Integration','Make existing tools work together seamlessly.'],['Tech Stack Consulting','Honest advice on the right tools for your business.'],['Custom Tool & App Development','Solutions built when nothing off-the-shelf fits.'],['CRM & ERP Setup','Configured systems your team will actually use.'],['Legacy System Modernization','Bring outdated systems up to modern standards.']], includes:[['Automation Setup','Using tools like Zapier, Make, and n8n.'],['CRM Integration','With platforms like HubSpot and Salesforce.'],['Internal Tool Development','For team-specific workflows.'],['API Development & Integration','Connect your systems.'],['Cloud Migration Support','Move off legacy infrastructure.'],['IT Process Consulting','Plan your technology roadmap.']], steps:[['Systems & Workflow Audit','Identify where time is being lost.'],['Solution Design','Map improvements to actual processes.'],['Build & Integration','Fit the work into existing systems.'],['Testing & Handover','Documentation your team can follow.']], audience:['Businesses doing repetitive manual work that could be automated','Companies juggling disconnected tools and software','Teams needing custom internal tools or integrations'], suggestions:['Ongoing Tech Support & Maintenance Retainers','AI-Powered Workflow Automation'], ...common },
}

export const serviceSlugs = Object.keys(serviceContent)

export function getServiceContent(slug: string): ServiceContent {
  const service = serviceContent[slug]
  if (!service) throw new Error(`Unknown service: ${slug}`)
  return service
}
