import Image from 'next/image'
import { notFound } from 'next/navigation'
import { ArrowDownRight, BarChart3, CalendarDays, CircleUserRound, TrendingUp } from 'lucide-react'
import { blogPosts, adoptionStages, cancellationReasons, postIntro, sections, useCases } from '@/lib/blog'

export function generateStaticParams() { return blogPosts.map((post) => ({ slug: post.slug })) }

const stageColors = ['bg-sky-500', 'bg-cyan-500', 'bg-violet-500', 'bg-emerald-500']
const barColors = ['bg-rose-500', 'bg-orange-400', 'bg-amber-300', 'bg-emerald-400', 'bg-sky-400', 'bg-indigo-400', 'bg-fuchsia-500', 'bg-pink-400', 'bg-slate-400']

function Highlight({ value, label, tone = 'primary' }: { value: string; label: string; tone?: 'primary' | 'accent' | 'secondary' }) {
  return <div className={`rounded-2xl p-5 ${tone === 'accent' ? 'bg-accent text-accent-foreground' : tone === 'secondary' ? 'bg-secondary text-secondary-foreground' : 'bg-primary text-primary-foreground'}`}><p className="text-3xl font-bold tracking-tight">{value}</p><p className="mt-1 text-sm font-medium opacity-85">{label}</p></div>
}

export default async function BlogArticle({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const post = blogPosts.find((item) => item.slug === slug)
  if (!post) notFound()
  return <main className="bg-background"><article className="mx-auto max-w-[1440px] px-4 py-10 sm:px-6 lg:px-10 lg:py-16">
    <header className="mx-auto max-w-5xl border-b border-border pb-10 text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">{post.category}</p><h1 className="mt-5 text-balance text-4xl font-bold tracking-tight text-foreground md:text-6xl">{post.title}</h1><p className="mx-auto mt-6 max-w-3xl text-xl leading-9 text-muted-foreground">{post.excerpt}</p><p className="mt-5 inline-flex items-center gap-2 text-sm text-muted-foreground"><CircleUserRound className="size-4" /> By <span className="font-semibold text-foreground">{post.author}</span><span aria-hidden="true">·</span><CalendarDays className="size-4" />{post.date}</p></header>
    <div className="relative mx-auto mt-10 aspect-[16/6] max-w-6xl overflow-hidden rounded-3xl"><Image src={post.cover} alt="Agentic AI adoption data visualization" fill priority sizes="(max-width: 896px) 100vw, 1200px" className="object-cover object-top" /></div>
    <div className="mt-12 grid gap-10 lg:grid-cols-[160px_minmax(0,1fr)_250px] lg:items-start">
      <aside className="hidden lg:block lg:sticky lg:top-24"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">In this story</p><nav className="mt-4 flex flex-col gap-3 text-sm text-muted-foreground"><a href="#definition" className="hover:text-primary">What counts</a><a href="#maturity" className="hover:text-primary">Maturity</a><a href="#results" className="hover:text-primary">Results</a><a href="#cancellations" className="hover:text-primary">Cancellations</a><a href="#business" className="hover:text-primary">Your business</a></nav></aside>
      <div className="min-w-0"><div className="space-y-6 text-lg leading-8 text-foreground/85">{postIntro.map((text) => <p key={text}>{text}</p>)}</div>
        <section id="definition" className="mt-14 scroll-mt-24"><SectionTitle index="01" title={sections[0].heading} /><p className="mt-6 text-lg leading-8 text-foreground/85">{sections[0].paragraphs[0]}</p></section>
        <section className="mt-14 scroll-mt-24"><SectionTitle index="02" title={sections[1].heading} />{sections[1].paragraphs.map((text) => <p className="mt-6 text-lg leading-8 text-foreground/85" key={text}>{text}</p>)}<div className="mt-8 grid gap-3 sm:grid-cols-3"><Highlight value="25%" label="Enterprise adoption" /><Highlight value="↑ fastest" label="Mid-market growth" tone="accent" /><Highlight value="15,000+" label="Businesses studied" tone="secondary" /></div></section>
        <section id="maturity" className="mt-14 scroll-mt-24"><SectionTitle index="03" title={sections[2].heading} /><p className="mt-6 text-lg leading-8 text-foreground/85">{sections[2].paragraphs[0]}</p><div className="mt-8 overflow-hidden rounded-2xl border border-border bg-card"><div className="flex items-center gap-3 border-b border-border bg-muted/50 p-5"><BarChart3 className="size-5 text-primary" /><h3 className="font-bold">Deployment maturity by company size</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="p-4 font-semibold">Stage</th><th className="p-4 font-semibold">Enterprise</th><th className="p-4 font-semibold">Mid-market</th><th className="p-4 font-semibold">SMB</th></tr></thead><tbody>{adoptionStages.map((row, index) => <tr className="border-b border-border last:border-0 odd:bg-muted/20" key={row[0]}><td className="p-4 font-semibold"><span className={`mr-2 inline-block size-2 rounded-full ${stageColors[index]}`} />{row[0]}</td>{row.slice(1).map((cell) => <td className="p-4 text-lg font-bold text-primary" key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></div><p className="mt-4 text-sm italic text-muted-foreground">Distribution of deployment stages among companies that have adopted agentic AI, 2026.</p><p className="mt-6 text-lg leading-8 text-foreground/85">{sections[2].paragraphs[1]}</p></section>
        <section id="results" className="mt-14 scroll-mt-24"><SectionTitle index="04" title={sections[3].heading} /><p className="mt-6 text-lg leading-8 text-foreground/85">{sections[3].paragraphs[0]}</p><div className="mt-8 space-y-4 rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="mb-5 flex items-center gap-3"><TrendingUp className="size-5 text-accent" /><h3 className="font-bold">Where adoption is delivering results</h3></div>{useCases.map(([name, value, note], index) => <div key={name}><div className="flex items-end justify-between gap-4"><p className="text-sm font-semibold text-foreground">{name}</p><strong className="text-xl text-primary">{value}</strong></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${barColors[index]}`} style={{ width: value }} /></div><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>)}</div><p className="mt-6 text-lg leading-8 text-foreground/85">{sections[3].paragraphs[1]}</p></section>
        <section id="cancellations" className="mt-14 scroll-mt-24"><SectionTitle index="05" title={sections[4].heading} /><p className="mt-6 text-lg leading-8 text-foreground/85">{sections[4].paragraphs[0]}</p><div className="mt-8 rounded-2xl border border-border bg-card p-5 sm:p-7"><h3 className="font-bold">Top reasons projects stall</h3><div className="mt-5 space-y-4">{cancellationReasons.map(([reason, value, segment], index) => <div className="grid grid-cols-[auto_1fr_auto] items-center gap-3" key={reason}><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span><div><p className="text-sm font-semibold">{reason}</p><div className="mt-1 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-accent" style={{ width: value }} /></div><p className="mt-1 text-xs text-muted-foreground">Most common in {segment}</p></div><strong className="text-lg text-primary">{value}</strong></div>)}</div></div><p className="mt-6 text-lg leading-8 text-foreground/85">{sections[4].paragraphs[1]}</p></section>
        <section id="business" className="mt-14 scroll-mt-24"><SectionTitle index="06" title={sections[5].heading} />{sections[5].paragraphs.map((text) => <p className="mt-6 text-lg leading-8 text-foreground/85" key={text}>{text}</p>)}<div className="mt-8 rounded-2xl bg-primary p-6 text-primary-foreground sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-accent">The practical takeaway</p><p className="mt-3 text-xl font-semibold leading-8">Start with one well-defined process, prove the measurable difference, and scale deliberately.</p></div></section>
      </div>
      <aside className="space-y-4 lg:sticky lg:top-24"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Key signals</p><Highlight value="82%" label="Customer conversations handled autonomously" /><Highlight value="40%+" label="Projects projected to be cancelled by 2027" tone="accent" /><div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm font-semibold">Read with context</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Adoption is rising, but maturity and preparation are what separate pilots from durable results.</p><ArrowDownRight className="mt-5 size-5 text-primary" /></div></aside>
    </div>
  </article></main>
}

function SectionTitle({ index, title }: { index: string; title: string }) { return <div className="flex items-start gap-4 border-t-2 border-primary pt-4"><span className="font-mono text-sm font-bold text-accent">{index}</span><h2 className="text-balance text-3xl font-bold tracking-tight text-foreground md:text-4xl">{title}</h2></div> }
